
DROP TABLE SEQ;

CREATE TABLE SEQ	(
	LAST_VAL INTEGER NOT NULL
);

INSERT INTO SEQ VALUES (10);

DROP TABLE PERSON;

CREATE TABLE PERSON	(
	ID INTEGER NOT NULL,
	FIRSTNAME VARCHAR(50),
	NAME VARCHAR(50),
	PRIMARY KEY (ID)
	); 
	
INSERT INTO PERSON VALUES (0,'Adrian', 'Bucher');
INSERT INTO PERSON VALUES (1,'Adrian', 'Egloff');
INSERT INTO PERSON VALUES (2,'Adrian', 'Moser');
INSERT INTO PERSON VALUES (3,'Adrian', 'Sacchi');


DROP TABLE ADDRESS;

CREATE TABLE ADDRESS	(
	ID INTEGER NOT NULL,
	PERSON_ID INTEGER NOT NULL,
	STREET VARCHAR(50),
	CITY VARCHAR(50),
	PRIMARY KEY (ID)
	); 


INSERT INTO ADDRESS VALUES (0,0, 'Baumgartenweg', 'Knonau');
INSERT INTO ADDRESS VALUES (1,1, 'Quartierstrasse', 'Wettingen');
INSERT INTO ADDRESS VALUES (2,2, 'General Weberstrasse', 'Frauenfeld');
INSERT INTO ADDRESS VALUES (3,3, 'Bühlplatz', 'Bern');


SELECT * FROM PERSON;