/**
 * 
 */
package com.bsiag.education.di.shared.services;

import java.util.Map;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.tablefield.AbstractTableFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class DesktopFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public DesktopFormData() {
  }

  public Name getName() {
    return getFieldByClass(Name.class);
  }

  public PersonTable getPersonTable() {
    return getFieldByClass(PersonTable.class);
  }

  public static class Name extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public Name() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class PersonTable extends AbstractTableFieldData {

    private static final long serialVersionUID = 1L;
    public static final int ID_COLUMN_ID = 0;
    public static final int PRENAME_COLUMN_ID = 1;
    public static final int NAME_COLUMN_ID = 2;

    public PersonTable() {
    }

    public Integer getId(int row) {
      return (Integer) getValueInternal(row, ID_COLUMN_ID);
    }

    public void setId(int row, Integer id) {
      setValueInternal(row, ID_COLUMN_ID, id);
    }

    public String getName(int row) {
      return (String) getValueInternal(row, NAME_COLUMN_ID);
    }

    public void setName(int row, String name) {
      setValueInternal(row, NAME_COLUMN_ID, name);
    }

    public String getPrename(int row) {
      return (String) getValueInternal(row, PRENAME_COLUMN_ID);
    }

    public void setPrename(int row, String prename) {
      setValueInternal(row, PRENAME_COLUMN_ID, prename);
    }

    @Override
    public int getColumnCount() {
      return 3;
    }

    @Override
    public Object getValueAt(int row, int column) {
      switch (column) {
        case ID_COLUMN_ID:
          return getId(row);
        case PRENAME_COLUMN_ID:
          return getPrename(row);
        case NAME_COLUMN_ID:
          return getName(row);
        default:
          return null;
      }
    }

    @Override
    public void setValueAt(int row, int column, Object value) {
      switch (column) {
        case ID_COLUMN_ID:
          setId(row, (Integer) value);
          break;
        case PRENAME_COLUMN_ID:
          setPrename(row, (String) value);
          break;
        case NAME_COLUMN_ID:
          setName(row, (String) value);
          break;
      }
    }
  }
}
