/**
 * 
 */
package com.bsiag.education.di.shared.services;

import java.util.Map;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class PersonFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public PersonFormData() {
  }

  public Name getName() {
    return getFieldByClass(Name.class);
  }

  /**
   * access method for property PersonNr.
   */
  public Long getPersonNr() {
    return getPersonNrProperty().getValue();
  }

  /**
   * access method for property PersonNr.
   */
  public void setPersonNr(Long personNr) {
    getPersonNrProperty().setValue(personNr);
  }

  public PersonNrProperty getPersonNrProperty() {
    return getPropertyByClass(PersonNrProperty.class);
  }

  public Prename getPrename() {
    return getFieldByClass(Prename.class);
  }

  public static class Name extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public Name() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class PersonNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;

    public PersonNrProperty() {
    }
  }

  public static class Prename extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public Prename() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }
}
